# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Laurent Brusa
tagline:          ''
description:      ''

baseurl:          /

author:
  name:           'Laurent Brusa'
  url:            https://twitter.com/

paginate:         5

# Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/multitudes/multitudes.github.io.git
