# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Laurence B
tagline:          'A Personal Site'
description:      ''

baseurl:          /

author:
  name:           'Laurence B'
  url:            https://twitter.com/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/multitudes/multitudes.github.io.git
