# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        :year/:month/:title:output_ext
#relative_permalinks: true

# Setup
title:            Laurent Brusa
tagline:          'We are Multitudes'
description:      'passionate coder'
node.url:         https://multitudes.github.io
baseurl:          /

author:
  name:           'laurent b'
  url:            https://twitter.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/multitudes/

#excerpt_separator: <!--more-->