# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Laurent Brusa
tagline:          'We are Multitudes'
description:      'my profile and blog'
url:              https://multitudes.github.io
baseurl:          /

author:
  name:           'laurent b'
  url:            https://twitter.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/multitudes/
